// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title INoirVerifier
/// @notice Interface for Noir UltraPlonk verifier generated by bb
interface INoirVerifier {
    /// @notice Verifies a proof
    /// @param _proof The proof bytes
    /// @param _publicInputs The public inputs to the circuit
    /// @return True if the proof is valid, false otherwise
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external view returns (bool);
}
